### PR TITLE
Create a Repository file if Declare Repository is checked

### PR DESCRIPTION
**Pull request by junichi11**
PR for #1

### CODE REVIEW

**Comment by Monomachus** [comment]
The repo folder is different than the entity one, and now the file is created in the same folder, so this should be fixed.

**Comment by junichi11** [comment]
Sorry, I can't fix it correctly if you don't write details because I don't know about symfony.
Is there the Repository directory at the same hierarchy as the Entity directory?
If so, create a repository file to it, otherwise do nothing. I'll fix like this.

Thanks.

**Comment by Monomachus** [comment]
Yeah basically the path to the Repository folder is in the variable [_repoNamespace_](https://github.com/nbphpcouncil/nb-symfony-templates-plugin/commit/8706d56f6b4e16db29a5fba763b94a2f0d703703#diff-87d1967a46b728f4c6191941965d6bf9R83) .
So we need the new repo file created in that folder

**Comment by junichi11** [comment]
I see. Thanks!

**Comment by junichi11** [comment]
@Monomachus I've fixed it. Could you try to use it?

**Comment by Monomachus** [comment]
@junichi11 Great, it is working.
One thing remaining is to check before creating the repo file, if a file with the same name already exists in folder. In that case we shouldn't create another file. 

Example: we create an Entity _Location_, in our repo folder we already have _LocationRepository_ in that case we shouldn't create another file.

**Comment by junichi11** [comment]
I've fixed it.

**Comment by Monomachus** [comment]
@junichi11 Great, I've tested it looks good to me. :+1:

**Pull request merged**
